// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: arc.sql

package sqlc

import (
	"context"
	"database/sql"
)

const linkArcIssue = `-- name: LinkArcIssue :exec
INSERT INTO story_arc_issues (arc_id, issue_id, position)
VALUES (?, ?, ?)
ON CONFLICT(arc_id, issue_id) DO UPDATE SET
  position = excluded.position
`

type LinkArcIssueParams struct {
	ArcID    int64
	IssueID  int64
	Position int64
}

func (q *Queries) LinkArcIssue(ctx context.Context, arg LinkArcIssueParams) error {
	_, err := q.db.ExecContext(ctx, linkArcIssue, arg.ArcID, arg.IssueID, arg.Position)
	return err
}

const listArcsBySeries = `-- name: ListArcsBySeries :many
SELECT DISTINCT sa.id, sa.comicvine_arc_id, sa.name, sa.created_at
FROM story_arcs sa
JOIN story_arc_issues sai ON sai.arc_id = sa.id
JOIN issues i ON i.id = sai.issue_id
WHERE i.series_id = ?
ORDER BY sa.name
`

func (q *Queries) ListArcsBySeries(ctx context.Context, seriesID int64) ([]StoryArc, error) {
	rows, err := q.db.QueryContext(ctx, listArcsBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoryArc{}
	for rows.Next() {
		var i StoryArc
		if err := rows.Scan(
			&i.ID,
			&i.ComicvineArcID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertArc = `-- name: UpsertArc :one
INSERT INTO story_arcs (comicvine_arc_id, name, created_at)
VALUES (?, ?, ?)
ON CONFLICT(comicvine_arc_id) DO UPDATE SET
  name = excluded.name
RETURNING id, comicvine_arc_id, name, created_at
`

type UpsertArcParams struct {
	ComicvineArcID sql.NullInt64
	Name           string
	CreatedAt      string
}

// Idempotent on the immutable comicvine_arc_id.
func (q *Queries) UpsertArc(ctx context.Context, arg UpsertArcParams) (StoryArc, error) {
	row := q.db.QueryRowContext(ctx, upsertArc, arg.ComicvineArcID, arg.Name, arg.CreatedAt)
	var i StoryArc
	err := row.Scan(
		&i.ID,
		&i.ComicvineArcID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
