// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blacklist.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addBlacklist = `-- name: AddBlacklist :exec
INSERT INTO blacklists (
  issue_id, series_id, provider, release_key, reason, created_at
) VALUES (
  ?, NULL, ?, ?, ?, ?
)
ON CONFLICT(provider, release_key, issue_id) DO NOTHING
`

type AddBlacklistParams struct {
	IssueID    sql.NullInt64
	Provider   string
	ReleaseKey string
	Reason     sql.NullString
	CreatedAt  string
}

// Per-issue blacklist of a specific release (D-11): issue_id is set, series_id is NULL
// (series-wide blacklist is deferred). The UNIQUE(provider, release_key, issue_id)
// constraint makes a duplicate blacklist of the same release for the same issue a no-op.
func (q *Queries) AddBlacklist(ctx context.Context, arg AddBlacklistParams) error {
	_, err := q.db.ExecContext(ctx, addBlacklist,
		arg.IssueID,
		arg.Provider,
		arg.ReleaseKey,
		arg.Reason,
		arg.CreatedAt,
	)
	return err
}

const listBlacklistForIssue = `-- name: ListBlacklistForIssue :many
SELECT provider, release_key FROM blacklists
WHERE issue_id = ?
`

type ListBlacklistForIssueRow struct {
	Provider   string
	ReleaseKey string
}

// The (provider, release_key) pairs a user has blacklisted for an issue (D-11). The
// replacement search unions these with the dead download keys to build its BlacklistSet.
func (q *Queries) ListBlacklistForIssue(ctx context.Context, issueID sql.NullInt64) ([]ListBlacklistForIssueRow, error) {
	rows, err := q.db.QueryContext(ctx, listBlacklistForIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlacklistForIssueRow{}
	for rows.Next() {
		var i ListBlacklistForIssueRow
		if err := rows.Scan(&i.Provider, &i.ReleaseKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
