// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comicvine_config.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getComicVineConfig = `-- name: GetComicVineConfig :one
SELECT id, api_key, created_at, updated_at FROM comicvine_config WHERE id = 1
`

func (q *Queries) GetComicVineConfig(ctx context.Context) (ComicvineConfig, error) {
	row := q.db.QueryRowContext(ctx, getComicVineConfig)
	var i ComicvineConfig
	err := row.Scan(
		&i.ID,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertComicVineConfig = `-- name: UpsertComicVineConfig :one
INSERT INTO comicvine_config (
  id, api_key, created_at, updated_at
) VALUES (
  1, ?, ?, ?
)
ON CONFLICT(id) DO UPDATE SET
  api_key    = excluded.api_key,
  updated_at = excluded.updated_at
RETURNING id, api_key, created_at, updated_at
`

type UpsertComicVineConfigParams struct {
	ApiKey    sql.NullString
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) UpsertComicVineConfig(ctx context.Context, arg UpsertComicVineConfigParams) (ComicvineConfig, error) {
	row := q.db.QueryRowContext(ctx, upsertComicVineConfig, arg.ApiKey, arg.CreatedAt, arg.UpdatedAt)
	var i ComicvineConfig
	err := row.Scan(
		&i.ID,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
