// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: covers.sql

package sqlc

import (
	"context"
)

const coverExists = `-- name: CoverExists :one
SELECT EXISTS(SELECT 1 FROM covers WHERE entity_type = ? AND entity_id = ?)
`

type CoverExistsParams struct {
	EntityType string
	EntityID   int64
}

func (q *Queries) CoverExists(ctx context.Context, arg CoverExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, coverExists, arg.EntityType, arg.EntityID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getCover = `-- name: GetCover :one
SELECT image, content_type FROM covers WHERE entity_type = ? AND entity_id = ?
`

type GetCoverParams struct {
	EntityType string
	EntityID   int64
}

type GetCoverRow struct {
	Image       []byte
	ContentType string
}

func (q *Queries) GetCover(ctx context.Context, arg GetCoverParams) (GetCoverRow, error) {
	row := q.db.QueryRowContext(ctx, getCover, arg.EntityType, arg.EntityID)
	var i GetCoverRow
	err := row.Scan(&i.Image, &i.ContentType)
	return i, err
}

const upsertCover = `-- name: UpsertCover :exec
INSERT INTO covers (entity_type, entity_id, image, content_type, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(entity_type, entity_id) DO UPDATE SET
  image        = excluded.image,
  content_type = excluded.content_type,
  updated_at   = excluded.updated_at
`

type UpsertCoverParams struct {
	EntityType  string
	EntityID    int64
	Image       []byte
	ContentType string
	UpdatedAt   string
}

// Idempotent upsert of a cover blob keyed on (entity_type, entity_id).
func (q *Queries) UpsertCover(ctx context.Context, arg UpsertCoverParams) error {
	_, err := q.db.ExecContext(ctx, upsertCover,
		arg.EntityType,
		arg.EntityID,
		arg.Image,
		arg.ContentType,
		arg.UpdatedAt,
	)
	return err
}
