// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: download.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createDownload = `-- name: CreateDownload :one
INSERT INTO downloads (
  issue_id, provider, release_key, release_title, size_bytes, status, client_ref,
  created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(provider, release_key, issue_id) DO UPDATE SET
  release_title = excluded.release_title,
  size_bytes    = excluded.size_bytes,
  status        = excluded.status,
  client_ref    = excluded.client_ref,
  updated_at    = excluded.updated_at
RETURNING id, issue_id, provider, release_key, release_title, size_bytes, status, client_ref, created_at, updated_at
`

type CreateDownloadParams struct {
	IssueID      int64
	Provider     string
	ReleaseKey   string
	ReleaseTitle sql.NullString
	SizeBytes    sql.NullInt64
	Status       string
	ClientRef    sql.NullString
	CreatedAt    string
	UpdatedAt    string
}

// Idempotent upsert on the existing UNIQUE(provider, release_key, issue_id) index:
// a duplicate grab of the same release for the same issue updates in place (T-4-02).
func (q *Queries) CreateDownload(ctx context.Context, arg CreateDownloadParams) (Download, error) {
	row := q.db.QueryRowContext(ctx, createDownload,
		arg.IssueID,
		arg.Provider,
		arg.ReleaseKey,
		arg.ReleaseTitle,
		arg.SizeBytes,
		arg.Status,
		arg.ClientRef,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Provider,
		&i.ReleaseKey,
		&i.ReleaseTitle,
		&i.SizeBytes,
		&i.Status,
		&i.ClientRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDownloadByID = `-- name: GetDownloadByID :one
SELECT id, issue_id, provider, release_key, release_title, size_bytes, status, client_ref, created_at, updated_at FROM downloads WHERE id = ?
`

func (q *Queries) GetDownloadByID(ctx context.Context, id int64) (Download, error) {
	row := q.db.QueryRowContext(ctx, getDownloadByID, id)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Provider,
		&i.ReleaseKey,
		&i.ReleaseTitle,
		&i.SizeBytes,
		&i.Status,
		&i.ClientRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDownloadsByIssue = `-- name: ListDownloadsByIssue :many
SELECT id, issue_id, provider, release_key, release_title, size_bytes, status, client_ref, created_at, updated_at FROM downloads WHERE issue_id = ? ORDER BY created_at
`

func (q *Queries) ListDownloadsByIssue(ctx context.Context, issueID int64) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadsByIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Download{}
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Provider,
			&i.ReleaseKey,
			&i.ReleaseTitle,
			&i.SizeBytes,
			&i.Status,
			&i.ClientRef,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
