// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: download_client.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getDownloadClientConfig = `-- name: GetDownloadClientConfig :one
SELECT id, url, api_key, category, created_at, updated_at FROM download_client_config WHERE id = 1
`

func (q *Queries) GetDownloadClientConfig(ctx context.Context) (DownloadClientConfig, error) {
	row := q.db.QueryRowContext(ctx, getDownloadClientConfig)
	var i DownloadClientConfig
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.ApiKey,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDownloadClientConfig = `-- name: UpsertDownloadClientConfig :one
INSERT INTO download_client_config (
  id, url, api_key, category, created_at, updated_at
) VALUES (
  1, ?, ?, ?, ?, ?
)
ON CONFLICT(id) DO UPDATE SET
  url        = excluded.url,
  api_key    = excluded.api_key,
  category   = excluded.category,
  updated_at = excluded.updated_at
RETURNING id, url, api_key, category, created_at, updated_at
`

type UpsertDownloadClientConfigParams struct {
	Url       string
	ApiKey    sql.NullString
	Category  string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) UpsertDownloadClientConfig(ctx context.Context, arg UpsertDownloadClientConfigParams) (DownloadClientConfig, error) {
	row := q.db.QueryRowContext(ctx, upsertDownloadClientConfig,
		arg.Url,
		arg.ApiKey,
		arg.Category,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i DownloadClientConfig
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.ApiKey,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
