// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: indexer.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createIndexer = `-- name: CreateIndexer :one
INSERT INTO indexers (
  name, kind, base_url, api_key, enabled, categories, priority, use_for_rss,
  created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, name, kind, base_url, api_key, enabled, categories, priority, use_for_rss, created_at, updated_at
`

type CreateIndexerParams struct {
	Name       string
	Kind       string
	BaseUrl    string
	ApiKey     sql.NullString
	Enabled    int64
	Categories sql.NullString
	Priority   int64
	UseForRss  int64
	CreatedAt  string
	UpdatedAt  string
}

func (q *Queries) CreateIndexer(ctx context.Context, arg CreateIndexerParams) (Indexer, error) {
	row := q.db.QueryRowContext(ctx, createIndexer,
		arg.Name,
		arg.Kind,
		arg.BaseUrl,
		arg.ApiKey,
		arg.Enabled,
		arg.Categories,
		arg.Priority,
		arg.UseForRss,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Indexer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Enabled,
		&i.Categories,
		&i.Priority,
		&i.UseForRss,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIndexer = `-- name: DeleteIndexer :exec
DELETE FROM indexers WHERE id = ?
`

func (q *Queries) DeleteIndexer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteIndexer, id)
	return err
}

const getIndexer = `-- name: GetIndexer :one
SELECT id, name, kind, base_url, api_key, enabled, categories, priority, use_for_rss, created_at, updated_at FROM indexers WHERE id = ?
`

func (q *Queries) GetIndexer(ctx context.Context, id int64) (Indexer, error) {
	row := q.db.QueryRowContext(ctx, getIndexer, id)
	var i Indexer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Enabled,
		&i.Categories,
		&i.Priority,
		&i.UseForRss,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledIndexers = `-- name: ListEnabledIndexers :many
SELECT id, name, kind, base_url, api_key, enabled, categories, priority, use_for_rss, created_at, updated_at FROM indexers
WHERE enabled = 1
ORDER BY priority, name
`

func (q *Queries) ListEnabledIndexers(ctx context.Context) ([]Indexer, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledIndexers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Indexer{}
	for rows.Next() {
		var i Indexer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.BaseUrl,
			&i.ApiKey,
			&i.Enabled,
			&i.Categories,
			&i.Priority,
			&i.UseForRss,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIndexers = `-- name: ListIndexers :many
SELECT id, name, kind, base_url, api_key, enabled, categories, priority, use_for_rss, created_at, updated_at FROM indexers
ORDER BY priority, name
`

func (q *Queries) ListIndexers(ctx context.Context) ([]Indexer, error) {
	rows, err := q.db.QueryContext(ctx, listIndexers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Indexer{}
	for rows.Next() {
		var i Indexer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.BaseUrl,
			&i.ApiKey,
			&i.Enabled,
			&i.Categories,
			&i.Priority,
			&i.UseForRss,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIndexer = `-- name: UpdateIndexer :one
UPDATE indexers SET
  name        = ?,
  kind        = ?,
  base_url    = ?,
  api_key     = ?,
  enabled     = ?,
  categories  = ?,
  priority    = ?,
  use_for_rss = ?,
  updated_at  = ?
WHERE id = ?
RETURNING id, name, kind, base_url, api_key, enabled, categories, priority, use_for_rss, created_at, updated_at
`

type UpdateIndexerParams struct {
	Name       string
	Kind       string
	BaseUrl    string
	ApiKey     sql.NullString
	Enabled    int64
	Categories sql.NullString
	Priority   int64
	UseForRss  int64
	UpdatedAt  string
	ID         int64
}

func (q *Queries) UpdateIndexer(ctx context.Context, arg UpdateIndexerParams) (Indexer, error) {
	row := q.db.QueryRowContext(ctx, updateIndexer,
		arg.Name,
		arg.Kind,
		arg.BaseUrl,
		arg.ApiKey,
		arg.Enabled,
		arg.Categories,
		arg.Priority,
		arg.UseForRss,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Indexer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Enabled,
		&i.Categories,
		&i.Priority,
		&i.UseForRss,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
