// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issue.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countIssuesBySeries = `-- name: CountIssuesBySeries :one
SELECT count(*) FROM issues WHERE series_id = ?
`

func (q *Queries) CountIssuesBySeries(ctx context.Context, seriesID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIssuesBySeries, seriesID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listIssuesBySeries = `-- name: ListIssuesBySeries :many
SELECT id, series_id, comicvine_issue_id, issue_number_raw, issue_number_sort, issue_number_qual, title, cover_date, store_date, release_date, status, search_attempts, location, created_at FROM issues
WHERE series_id = ?
ORDER BY issue_number_sort, COALESCE(issue_number_qual, '')
`

func (q *Queries) ListIssuesBySeries(ctx context.Context, seriesID int64) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, listIssuesBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.ComicvineIssueID,
			&i.IssueNumberRaw,
			&i.IssueNumberSort,
			&i.IssueNumberQual,
			&i.Title,
			&i.CoverDate,
			&i.StoreDate,
			&i.ReleaseDate,
			&i.Status,
			&i.SearchAttempts,
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIssueStatus = `-- name: UpdateIssueStatus :exec
UPDATE issues SET status = ?, search_attempts = ? WHERE id = ?
`

type UpdateIssueStatusParams struct {
	Status         string
	SearchAttempts int64
	ID             int64
}

func (q *Queries) UpdateIssueStatus(ctx context.Context, arg UpdateIssueStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateIssueStatus, arg.Status, arg.SearchAttempts, arg.ID)
	return err
}

const upsertIssue = `-- name: UpsertIssue :one
INSERT INTO issues (
  series_id, comicvine_issue_id, issue_number_raw, issue_number_sort,
  issue_number_qual, title, cover_date, store_date, release_date,
  status, created_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(comicvine_issue_id) DO UPDATE SET
  issue_number_raw  = excluded.issue_number_raw,
  issue_number_sort = excluded.issue_number_sort,
  issue_number_qual = excluded.issue_number_qual,
  title             = excluded.title,
  cover_date        = excluded.cover_date,
  store_date        = excluded.store_date,
  release_date      = excluded.release_date
RETURNING id, series_id, comicvine_issue_id, issue_number_raw, issue_number_sort, issue_number_qual, title, cover_date, store_date, release_date, status, search_attempts, location, created_at
`

type UpsertIssueParams struct {
	SeriesID         int64
	ComicvineIssueID int64
	IssueNumberRaw   string
	IssueNumberSort  float64
	IssueNumberQual  sql.NullString
	Title            sql.NullString
	CoverDate        sql.NullString
	StoreDate        sql.NullString
	ReleaseDate      sql.NullString
	Status           string
	CreatedAt        string
}

// Idempotent upsert keyed on the immutable comicvine_issue_id (D-04).
func (q *Queries) UpsertIssue(ctx context.Context, arg UpsertIssueParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, upsertIssue,
		arg.SeriesID,
		arg.ComicvineIssueID,
		arg.IssueNumberRaw,
		arg.IssueNumberSort,
		arg.IssueNumberQual,
		arg.Title,
		arg.CoverDate,
		arg.StoreDate,
		arg.ReleaseDate,
		arg.Status,
		arg.CreatedAt,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.ComicvineIssueID,
		&i.IssueNumberRaw,
		&i.IssueNumberSort,
		&i.IssueNumberQual,
		&i.Title,
		&i.CoverDate,
		&i.StoreDate,
		&i.ReleaseDate,
		&i.Status,
		&i.SearchAttempts,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}
