// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issue_event.sql

package sqlc

import (
	"context"
	"database/sql"
)

const insertIssueEvent = `-- name: InsertIssueEvent :one
INSERT INTO issue_events (issue_id, event_type, payload_json, occurred_at)
VALUES (?, ?, ?, ?)
RETURNING id, issue_id, event_type, payload_json, occurred_at
`

type InsertIssueEventParams struct {
	IssueID     int64
	EventType   string
	PayloadJson sql.NullString
	OccurredAt  string
}

func (q *Queries) InsertIssueEvent(ctx context.Context, arg InsertIssueEventParams) (IssueEvent, error) {
	row := q.db.QueryRowContext(ctx, insertIssueEvent,
		arg.IssueID,
		arg.EventType,
		arg.PayloadJson,
		arg.OccurredAt,
	)
	var i IssueEvent
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.EventType,
		&i.PayloadJson,
		&i.OccurredAt,
	)
	return i, err
}

const listIssueEventsByIssue = `-- name: ListIssueEventsByIssue :many
SELECT id, issue_id, event_type, payload_json, occurred_at FROM issue_events WHERE issue_id = ? ORDER BY occurred_at, id
`

func (q *Queries) ListIssueEventsByIssue(ctx context.Context, issueID int64) ([]IssueEvent, error) {
	rows, err := q.db.QueryContext(ctx, listIssueEventsByIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueEvent{}
	for rows.Next() {
		var i IssueEvent
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.EventType,
			&i.PayloadJson,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
