// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issue.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countIssuesBySeries = `-- name: CountIssuesBySeries :one
SELECT count(*) FROM issues WHERE series_id = ?
`

func (q *Queries) CountIssuesBySeries(ctx context.Context, seriesID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIssuesBySeries, seriesID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getIssueByID = `-- name: GetIssueByID :one
SELECT id, series_id, comicvine_issue_id, issue_number_raw, issue_number_sort, issue_number_qual, title, cover_date, store_date, release_date, description, image_url, cv_last_updated, issue_type, alt_issue_number, page_count, status, search_attempts, location, created_at, download_attempts FROM issues WHERE id = ?
`

func (q *Queries) GetIssueByID(ctx context.Context, id int64) (Issue, error) {
	row := q.db.QueryRowContext(ctx, getIssueByID, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.ComicvineIssueID,
		&i.IssueNumberRaw,
		&i.IssueNumberSort,
		&i.IssueNumberQual,
		&i.Title,
		&i.CoverDate,
		&i.StoreDate,
		&i.ReleaseDate,
		&i.Description,
		&i.ImageUrl,
		&i.CvLastUpdated,
		&i.IssueType,
		&i.AltIssueNumber,
		&i.PageCount,
		&i.Status,
		&i.SearchAttempts,
		&i.Location,
		&i.CreatedAt,
		&i.DownloadAttempts,
	)
	return i, err
}

const incrementDownloadAttempts = `-- name: IncrementDownloadAttempts :exec
UPDATE issues SET download_attempts = download_attempts + 1 WHERE id = ?
`

// Records a failed-grab / replacement cycle for an issue (D-13). download_attempts is
// SEPARATE from search_attempts: it counts dead downloads, not no-result searches. The
// growing count crosses the cap and parks the issue in cool-off (D-14).
func (q *Queries) IncrementDownloadAttempts(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementDownloadAttempts, id)
	return err
}

const incrementSearchAttempts = `-- name: IncrementSearchAttempts :exec
UPDATE issues SET search_attempts = search_attempts + 1 WHERE id = ?
`

// Records a no-result auto-search attempt; the growing count spaces retries and
// eventually crosses the cap so the issue goes cold (D-09).
func (q *Queries) IncrementSearchAttempts(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementSearchAttempts, id)
	return err
}

const listIssuesBySeries = `-- name: ListIssuesBySeries :many
SELECT id, series_id, comicvine_issue_id, issue_number_raw, issue_number_sort, issue_number_qual, title, cover_date, store_date, release_date, description, image_url, cv_last_updated, issue_type, alt_issue_number, page_count, status, search_attempts, location, created_at, download_attempts FROM issues
WHERE series_id = ?
ORDER BY issue_number_sort, COALESCE(issue_number_qual, '')
`

func (q *Queries) ListIssuesBySeries(ctx context.Context, seriesID int64) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, listIssuesBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.ComicvineIssueID,
			&i.IssueNumberRaw,
			&i.IssueNumberSort,
			&i.IssueNumberQual,
			&i.Title,
			&i.CoverDate,
			&i.StoreDate,
			&i.ReleaseDate,
			&i.Description,
			&i.ImageUrl,
			&i.CvLastUpdated,
			&i.IssueType,
			&i.AltIssueNumber,
			&i.PageCount,
			&i.Status,
			&i.SearchAttempts,
			&i.Location,
			&i.CreatedAt,
			&i.DownloadAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWantedForAutoSearch = `-- name: ListWantedForAutoSearch :many
SELECT id, series_id, comicvine_issue_id, issue_number_raw, issue_number_sort, issue_number_qual, title, cover_date, store_date, release_date, description, image_url, cv_last_updated, issue_type, alt_issue_number, page_count, status, search_attempts, location, created_at, download_attempts FROM issues
WHERE status = 'Wanted' AND search_attempts < ?
ORDER BY search_attempts ASC, created_at ASC
LIMIT ?
`

type ListWantedForAutoSearchParams struct {
	SearchAttempts int64
	Limit          int64
}

// Bounded batch of Wanted issues eligible for auto-search: fewest search_attempts
// first (then oldest), excluding issues that have reached the attempt cap (cold).
// The cap is passed as the upper bound (D-08/D-09).
func (q *Queries) ListWantedForAutoSearch(ctx context.Context, arg ListWantedForAutoSearchParams) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, listWantedForAutoSearch, arg.SearchAttempts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.ComicvineIssueID,
			&i.IssueNumberRaw,
			&i.IssueNumberSort,
			&i.IssueNumberQual,
			&i.Title,
			&i.CoverDate,
			&i.StoreDate,
			&i.ReleaseDate,
			&i.Description,
			&i.ImageUrl,
			&i.CvLastUpdated,
			&i.IssueType,
			&i.AltIssueNumber,
			&i.PageCount,
			&i.Status,
			&i.SearchAttempts,
			&i.Location,
			&i.CreatedAt,
			&i.DownloadAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWantedForDownloadRetry = `-- name: ListWantedForDownloadRetry :many
SELECT id, series_id, comicvine_issue_id, issue_number_raw, issue_number_sort, issue_number_qual, title, cover_date, store_date, release_date, description, image_url, cv_last_updated, issue_type, alt_issue_number, page_count, status, search_attempts, location, created_at, download_attempts FROM issues
WHERE download_attempts < ?
ORDER BY download_attempts ASC, created_at ASC
LIMIT ?
`

type ListWantedForDownloadRetryParams struct {
	DownloadAttempts int64
	Limit            int64
}

// A bounded batch of issues eligible for an attempt-capped replacement, mirroring the
// search backoff but on the SEPARATE download_attempts counter (D-13/D-14): fewest
// download_attempts first (then oldest), excluding issues at or above the cap (cool-off).
func (q *Queries) ListWantedForDownloadRetry(ctx context.Context, arg ListWantedForDownloadRetryParams) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, listWantedForDownloadRetry, arg.DownloadAttempts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.ComicvineIssueID,
			&i.IssueNumberRaw,
			&i.IssueNumberSort,
			&i.IssueNumberQual,
			&i.Title,
			&i.CoverDate,
			&i.StoreDate,
			&i.ReleaseDate,
			&i.Description,
			&i.ImageUrl,
			&i.CvLastUpdated,
			&i.IssueType,
			&i.AltIssueNumber,
			&i.PageCount,
			&i.Status,
			&i.SearchAttempts,
			&i.Location,
			&i.CreatedAt,
			&i.DownloadAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWantedForMatch = `-- name: ListWantedForMatch :many
SELECT id, series_id, comicvine_issue_id, issue_number_raw, issue_number_sort, issue_number_qual, title, cover_date, store_date, release_date, description, image_url, cv_last_updated, issue_type, alt_issue_number, page_count, status, search_attempts, location, created_at, download_attempts FROM issues
WHERE status = 'Wanted'
ORDER BY series_id, issue_number_sort
`

// All currently-Wanted issues with their normalized sort/qual, for RSS feed matching.
func (q *Queries) ListWantedForMatch(ctx context.Context) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, listWantedForMatch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.ComicvineIssueID,
			&i.IssueNumberRaw,
			&i.IssueNumberSort,
			&i.IssueNumberQual,
			&i.Title,
			&i.CoverDate,
			&i.StoreDate,
			&i.ReleaseDate,
			&i.Description,
			&i.ImageUrl,
			&i.CvLastUpdated,
			&i.IssueType,
			&i.AltIssueNumber,
			&i.PageCount,
			&i.Status,
			&i.SearchAttempts,
			&i.Location,
			&i.CreatedAt,
			&i.DownloadAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetDownloadAttempts = `-- name: ResetDownloadAttempts :exec
UPDATE issues SET download_attempts = 0 WHERE id = ?
`

// Clears the download_attempts cool-off so a manual retry can re-run the pipeline
// immediately (DL-07 / D-14): the user's explicit retry is the intended cap reset.
func (q *Queries) ResetDownloadAttempts(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, resetDownloadAttempts, id)
	return err
}

const updateIssueStatus = `-- name: UpdateIssueStatus :exec
UPDATE issues SET status = ?, search_attempts = ? WHERE id = ?
`

type UpdateIssueStatusParams struct {
	Status         string
	SearchAttempts int64
	ID             int64
}

func (q *Queries) UpdateIssueStatus(ctx context.Context, arg UpdateIssueStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateIssueStatus, arg.Status, arg.SearchAttempts, arg.ID)
	return err
}

const upsertIssue = `-- name: UpsertIssue :one
INSERT INTO issues (
  series_id, comicvine_issue_id, issue_number_raw, issue_number_sort,
  issue_number_qual, title, cover_date, store_date, release_date,
  description, image_url, cv_last_updated, issue_type, alt_issue_number,
  page_count, status, created_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(comicvine_issue_id) DO UPDATE SET
  issue_number_raw  = excluded.issue_number_raw,
  issue_number_sort = excluded.issue_number_sort,
  issue_number_qual = excluded.issue_number_qual,
  title             = excluded.title,
  cover_date        = excluded.cover_date,
  store_date        = excluded.store_date,
  release_date      = excluded.release_date,
  description       = excluded.description,
  image_url         = excluded.image_url,
  cv_last_updated   = excluded.cv_last_updated,
  issue_type        = excluded.issue_type,
  alt_issue_number  = excluded.alt_issue_number,
  page_count        = excluded.page_count
RETURNING id, series_id, comicvine_issue_id, issue_number_raw, issue_number_sort, issue_number_qual, title, cover_date, store_date, release_date, description, image_url, cv_last_updated, issue_type, alt_issue_number, page_count, status, search_attempts, location, created_at, download_attempts
`

type UpsertIssueParams struct {
	SeriesID         int64
	ComicvineIssueID int64
	IssueNumberRaw   string
	IssueNumberSort  float64
	IssueNumberQual  sql.NullString
	Title            sql.NullString
	CoverDate        sql.NullString
	StoreDate        sql.NullString
	ReleaseDate      sql.NullString
	Description      sql.NullString
	ImageUrl         sql.NullString
	CvLastUpdated    sql.NullString
	IssueType        string
	AltIssueNumber   sql.NullString
	PageCount        sql.NullInt64
	Status           string
	CreatedAt        string
}

// Idempotent upsert keyed on the immutable comicvine_issue_id.
func (q *Queries) UpsertIssue(ctx context.Context, arg UpsertIssueParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, upsertIssue,
		arg.SeriesID,
		arg.ComicvineIssueID,
		arg.IssueNumberRaw,
		arg.IssueNumberSort,
		arg.IssueNumberQual,
		arg.Title,
		arg.CoverDate,
		arg.StoreDate,
		arg.ReleaseDate,
		arg.Description,
		arg.ImageUrl,
		arg.CvLastUpdated,
		arg.IssueType,
		arg.AltIssueNumber,
		arg.PageCount,
		arg.Status,
		arg.CreatedAt,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.ComicvineIssueID,
		&i.IssueNumberRaw,
		&i.IssueNumberSort,
		&i.IssueNumberQual,
		&i.Title,
		&i.CoverDate,
		&i.StoreDate,
		&i.ReleaseDate,
		&i.Description,
		&i.ImageUrl,
		&i.CvLastUpdated,
		&i.IssueType,
		&i.AltIssueNumber,
		&i.PageCount,
		&i.Status,
		&i.SearchAttempts,
		&i.Location,
		&i.CreatedAt,
		&i.DownloadAttempts,
	)
	return i, err
}
