// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issue_credit.sql

package sqlc

import (
	"context"
)

const deleteIssueCredits = `-- name: DeleteIssueCredits :exec
DELETE FROM issue_credits WHERE issue_id = ?
`

// Removes all credit rows for an issue, so Replace can rebuild them idempotently.
func (q *Queries) DeleteIssueCredits(ctx context.Context, issueID int64) error {
	_, err := q.db.ExecContext(ctx, deleteIssueCredits, issueID)
	return err
}

const insertIssueCredit = `-- name: InsertIssueCredit :exec
INSERT INTO issue_credits (issue_id, role, name, cv_person_id)
VALUES (?, ?, ?, ?)
ON CONFLICT DO NOTHING
`

type InsertIssueCreditParams struct {
	IssueID    int64
	Role       string
	Name       string
	CvPersonID int64
}

// Inserts one normalized credit; duplicate (issue_id, role, name) rows are no-ops.
func (q *Queries) InsertIssueCredit(ctx context.Context, arg InsertIssueCreditParams) error {
	_, err := q.db.ExecContext(ctx, insertIssueCredit,
		arg.IssueID,
		arg.Role,
		arg.Name,
		arg.CvPersonID,
	)
	return err
}

const listIssueCredits = `-- name: ListIssueCredits :many
SELECT issue_id, role, name, cv_person_id FROM issue_credits WHERE issue_id = ? ORDER BY role, name
`

func (q *Queries) ListIssueCredits(ctx context.Context, issueID int64) ([]IssueCredit, error) {
	rows, err := q.db.QueryContext(ctx, listIssueCredits, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueCredit{}
	for rows.Next() {
		var i IssueCredit
		if err := rows.Scan(
			&i.IssueID,
			&i.Role,
			&i.Name,
			&i.CvPersonID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
