// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metadata_provider_config.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getMetadataProviderConfig = `-- name: GetMetadataProviderConfig :one
SELECT provider, api_key, created_at, updated_at FROM metadata_provider_config WHERE provider = ?
`

func (q *Queries) GetMetadataProviderConfig(ctx context.Context, provider string) (MetadataProviderConfig, error) {
	row := q.db.QueryRowContext(ctx, getMetadataProviderConfig, provider)
	var i MetadataProviderConfig
	err := row.Scan(
		&i.Provider,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMetadataProviderConfig = `-- name: UpsertMetadataProviderConfig :one
INSERT INTO metadata_provider_config (
  provider, api_key, created_at, updated_at
) VALUES (
  ?, ?, ?, ?
)
ON CONFLICT(provider) DO UPDATE SET
  api_key    = excluded.api_key,
  updated_at = excluded.updated_at
RETURNING provider, api_key, created_at, updated_at
`

type UpsertMetadataProviderConfigParams struct {
	Provider  string
	ApiKey    sql.NullString
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) UpsertMetadataProviderConfig(ctx context.Context, arg UpsertMetadataProviderConfigParams) (MetadataProviderConfig, error) {
	row := q.db.QueryRowContext(ctx, upsertMetadataProviderConfig,
		arg.Provider,
		arg.ApiKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i MetadataProviderConfig
	err := row.Scan(
		&i.Provider,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
