// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metadata_cache.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getMetadataCache = `-- name: GetMetadataCache :one
SELECT id, cache_key, payload, source_updated_at, fetched_at FROM metadata_cache WHERE cache_key = ?
`

func (q *Queries) GetMetadataCache(ctx context.Context, cacheKey string) (MetadataCache, error) {
	row := q.db.QueryRowContext(ctx, getMetadataCache, cacheKey)
	var i MetadataCache
	err := row.Scan(
		&i.ID,
		&i.CacheKey,
		&i.Payload,
		&i.SourceUpdatedAt,
		&i.FetchedAt,
	)
	return i, err
}

const putMetadataCache = `-- name: PutMetadataCache :exec
INSERT INTO metadata_cache (cache_key, payload, source_updated_at, fetched_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(cache_key) DO UPDATE SET
  payload           = excluded.payload,
  source_updated_at = excluded.source_updated_at,
  fetched_at        = excluded.fetched_at
`

type PutMetadataCacheParams struct {
	CacheKey        string
	Payload         string
	SourceUpdatedAt sql.NullString
	FetchedAt       string
}

// Idempotent on cache_key (UNIQUE); refreshes payload + freshness markers (META-04/05).
func (q *Queries) PutMetadataCache(ctx context.Context, arg PutMetadataCacheParams) error {
	_, err := q.db.ExecContext(ctx, putMetadataCache,
		arg.CacheKey,
		arg.Payload,
		arg.SourceUpdatedAt,
		arg.FetchedAt,
	)
	return err
}
