// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Blacklist struct {
	ID         int64
	IssueID    sql.NullInt64
	SeriesID   sql.NullInt64
	Provider   string
	ReleaseKey string
	Reason     sql.NullString
	CreatedAt  string
}

type Cover struct {
	EntityType  string
	EntityID    int64
	Image       []byte
	ContentType string
	UpdatedAt   string
}

type Download struct {
	ID           int64
	IssueID      int64
	Provider     string
	ReleaseKey   string
	ReleaseTitle sql.NullString
	SizeBytes    sql.NullInt64
	Status       string
	ClientRef    sql.NullString
	CreatedAt    string
	UpdatedAt    string
}

type DownloadClientConfig struct {
	ID        int64
	Url       string
	ApiKey    sql.NullString
	Category  string
	CreatedAt string
	UpdatedAt string
}

type DownloadHistory struct {
	ID         int64
	IssueID    int64
	Provider   string
	ReleaseKey string
	Result     string
	Detail     sql.NullString
	OccurredAt string
}

type Indexer struct {
	ID         int64
	Name       string
	Kind       string
	BaseUrl    string
	ApiKey     sql.NullString
	Enabled    int64
	Categories sql.NullString
	Priority   int64
	UseForRss  int64
	CreatedAt  string
	UpdatedAt  string
}

type Issue struct {
	ID               int64
	SeriesID         int64
	ComicvineIssueID int64
	IssueNumberRaw   string
	IssueNumberSort  float64
	IssueNumberQual  sql.NullString
	Title            sql.NullString
	CoverDate        sql.NullString
	StoreDate        sql.NullString
	ReleaseDate      sql.NullString
	Description      sql.NullString
	ImageUrl         sql.NullString
	CvLastUpdated    sql.NullString
	IssueType        string
	AltIssueNumber   sql.NullString
	PageCount        sql.NullInt64
	Status           string
	SearchAttempts   int64
	Location         sql.NullString
	CreatedAt        string
	DownloadAttempts int64
}

type IssueCredit struct {
	IssueID    int64
	Role       string
	Name       string
	CvPersonID int64
}

type IssueEvent struct {
	ID          int64
	IssueID     int64
	EventType   string
	PayloadJson sql.NullString
	OccurredAt  string
}

type MetadataCache struct {
	ID              int64
	CacheKey        string
	Payload         string
	SourceUpdatedAt sql.NullString
	FetchedAt       string
}

type MetadataProviderConfig struct {
	Provider  string
	ApiKey    sql.NullString
	CreatedAt string
	UpdatedAt string
}

type Publisher struct {
	ID                   int64
	ComicvinePublisherID sql.NullInt64
	Name                 string
	CreatedAt            string
}

type Series struct {
	ID                int64
	ComicvineVolumeID int64
	PublisherID       sql.NullInt64
	Name              string
	StartYear         sql.NullInt64
	Description       sql.NullString
	Status            string
	TotalIssues       int64
	HaveIssues        int64
	SettingsJson      sql.NullString
	LastRefreshedAt   sql.NullString
	CreatedAt         string
}

type StoryArc struct {
	ID             int64
	ComicvineArcID sql.NullInt64
	Name           string
	CreatedAt      string
}

type StoryArcIssue struct {
	ArcID    int64
	IssueID  int64
	Position int64
}

type UserConfig struct {
	Key   string
	Value string
}
