// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Blacklist struct {
	ID         int64
	IssueID    sql.NullInt64
	SeriesID   sql.NullInt64
	Provider   string
	ReleaseKey string
	Reason     sql.NullString
	CreatedAt  string
}

type Download struct {
	ID           int64
	IssueID      int64
	Provider     string
	ReleaseKey   string
	ReleaseTitle sql.NullString
	SizeBytes    sql.NullInt64
	Status       string
	ClientRef    sql.NullString
	CreatedAt    string
	UpdatedAt    string
}

type DownloadHistory struct {
	ID         int64
	IssueID    int64
	Provider   string
	ReleaseKey string
	Result     string
	Detail     sql.NullString
	OccurredAt string
}

type Issue struct {
	ID               int64
	SeriesID         int64
	ComicvineIssueID int64
	IssueNumberRaw   string
	IssueNumberSort  float64
	IssueNumberQual  sql.NullString
	Title            sql.NullString
	CoverDate        sql.NullString
	StoreDate        sql.NullString
	ReleaseDate      sql.NullString
	Status           string
	SearchAttempts   int64
	Location         sql.NullString
	CoverPath        sql.NullString
	CreatedAt        string
}

type IssueEvent struct {
	ID          int64
	IssueID     int64
	EventType   string
	PayloadJson sql.NullString
	OccurredAt  string
}

type Job struct {
	ID          int64
	Kind        string
	ArgsJson    sql.NullString
	State       string
	Attempts    int64
	ScheduledAt sql.NullString
	StartedAt   sql.NullString
	FinishedAt  sql.NullString
	Error       sql.NullString
	CreatedAt   string
}

type JobHistory struct {
	ID         int64
	JobID      sql.NullInt64
	Kind       string
	State      string
	Detail     sql.NullString
	OccurredAt string
}

type MetadataCache struct {
	ID              int64
	CacheKey        string
	Payload         string
	SourceUpdatedAt sql.NullString
	FetchedAt       string
}

type Publisher struct {
	ID                   int64
	ComicvinePublisherID sql.NullInt64
	Name                 string
	CreatedAt            string
}

type Series struct {
	ID                int64
	ComicvineVolumeID int64
	PublisherID       sql.NullInt64
	Name              string
	StartYear         sql.NullInt64
	Description       sql.NullString
	Status            string
	CoverPath         sql.NullString
	TotalIssues       int64
	HaveIssues        int64
	SettingsJson      sql.NullString
	LastRefreshedAt   sql.NullString
	CreatedAt         string
}

type StoryArc struct {
	ID             int64
	ComicvineArcID sql.NullInt64
	Name           string
	CreatedAt      string
}

type StoryArcIssue struct {
	ArcID    int64
	IssueID  int64
	Position int64
}

type UserConfig struct {
	Key   string
	Value string
}
