// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: publisher.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getPublisherByID = `-- name: GetPublisherByID :one
SELECT id, comicvine_publisher_id, name, created_at FROM publishers WHERE id = ?
`

func (q *Queries) GetPublisherByID(ctx context.Context, id int64) (Publisher, error) {
	row := q.db.QueryRowContext(ctx, getPublisherByID, id)
	var i Publisher
	err := row.Scan(
		&i.ID,
		&i.ComicvinePublisherID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const upsertPublisher = `-- name: UpsertPublisher :one
INSERT INTO publishers (comicvine_publisher_id, name, created_at)
VALUES (?, ?, ?)
ON CONFLICT(name) DO UPDATE SET
  comicvine_publisher_id = excluded.comicvine_publisher_id
RETURNING id, comicvine_publisher_id, name, created_at
`

type UpsertPublisherParams struct {
	ComicvinePublisherID sql.NullInt64
	Name                 string
	CreatedAt            string
}

// Idempotent on name (UNIQUE); records the CV publisher id when known.
func (q *Queries) UpsertPublisher(ctx context.Context, arg UpsertPublisherParams) (Publisher, error) {
	row := q.db.QueryRowContext(ctx, upsertPublisher, arg.ComicvinePublisherID, arg.Name, arg.CreatedAt)
	var i Publisher
	err := row.Scan(
		&i.ID,
		&i.ComicvinePublisherID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
