// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CountIssuesBySeries(ctx context.Context, seriesID int64) (int64, error)
	CoverExists(ctx context.Context, arg CoverExistsParams) (bool, error)
	// Idempotent upsert on the existing UNIQUE(provider, release_key, issue_id) index:
	// a duplicate grab of the same release for the same issue updates in place (T-4-02).
	CreateDownload(ctx context.Context, arg CreateDownloadParams) (Download, error)
	CreateIndexer(ctx context.Context, arg CreateIndexerParams) (Indexer, error)
	DeleteIndexer(ctx context.Context, id int64) error
	// Removes all credit rows for an issue, so Replace can rebuild them idempotently.
	DeleteIssueCredits(ctx context.Context, issueID int64) error
	GetCover(ctx context.Context, arg GetCoverParams) (GetCoverRow, error)
	GetDownloadByID(ctx context.Context, id int64) (Download, error)
	GetDownloadClientConfig(ctx context.Context) (DownloadClientConfig, error)
	GetIndexer(ctx context.Context, id int64) (Indexer, error)
	GetIssueByID(ctx context.Context, id int64) (Issue, error)
	GetMetadataCache(ctx context.Context, cacheKey string) (MetadataCache, error)
	GetPublisherByID(ctx context.Context, id int64) (Publisher, error)
	GetSeriesByID(ctx context.Context, id int64) (Series, error)
	GetSeriesByVolumeID(ctx context.Context, comicvineVolumeID int64) (Series, error)
	GetUserConfig(ctx context.Context, key string) (UserConfig, error)
	// Records a no-result auto-search attempt; the growing count spaces retries and
	// eventually crosses the cap so the issue goes cold (D-09).
	IncrementSearchAttempts(ctx context.Context, id int64) error
	// Append-only download history (DL-03): record what was grabbed, from where, the outcome,
	// and when. Never updated or deleted; it is the audit trail of every grab + terminal flip.
	InsertDownloadHistory(ctx context.Context, arg InsertDownloadHistoryParams) (DownloadHistory, error)
	// Inserts one normalized credit; duplicate (issue_id, role, name) rows are no-ops.
	InsertIssueCredit(ctx context.Context, arg InsertIssueCreditParams) error
	InsertIssueEvent(ctx context.Context, arg InsertIssueEventParams) (IssueEvent, error)
	LinkArcIssue(ctx context.Context, arg LinkArcIssueParams) error
	// The active poll set: rows still in flight (Queued/Downloading) that the DownloadPoll
	// job polls SAB for each tick. Ordered oldest-updated-first so the most stale rows are
	// reconciled first within a bounded tick (D-01).
	ListActiveDownloads(ctx context.Context) ([]Download, error)
	ListArcsBySeries(ctx context.Context, seriesID int64) ([]StoryArc, error)
	// The (provider, release_key) pairs already known-bad for an issue: rows with a
	// Failed/Blacklisted downloads status. The replacement search excludes these so a
	// retry cannot re-pick a release that already failed for this issue (D-12 loop-prevention:
	// dedup against the downloads table, NOT the blacklists table).
	ListDeadReleaseKeysForIssue(ctx context.Context, issueID int64) ([]ListDeadReleaseKeysForIssueRow, error)
	ListDownloadsByIssue(ctx context.Context, issueID int64) ([]Download, error)
	ListEnabledIndexers(ctx context.Context) ([]Indexer, error)
	ListIndexers(ctx context.Context) ([]Indexer, error)
	ListIssueCredits(ctx context.Context, issueID int64) ([]IssueCredit, error)
	ListIssueEventsByIssue(ctx context.Context, issueID int64) ([]IssueEvent, error)
	ListIssuesBySeries(ctx context.Context, seriesID int64) ([]Issue, error)
	ListSeries(ctx context.Context, arg ListSeriesParams) ([]Series, error)
	// Active series never refreshed (NULL) or last refreshed before the cutoff, oldest
	// first (NULLs lead). Bounded by LIMIT to keep each sweep tick small. Paused/Ended
	// series are excluded: they are not being watched for freshness.
	ListStaleSeries(ctx context.Context, arg ListStaleSeriesParams) ([]Series, error)
	ListUserConfig(ctx context.Context) ([]UserConfig, error)
	// Bounded batch of Wanted issues eligible for auto-search: fewest search_attempts
	// first (then oldest), excluding issues that have reached the attempt cap (cold).
	// The cap is passed as the upper bound (D-08/D-09).
	ListWantedForAutoSearch(ctx context.Context, arg ListWantedForAutoSearchParams) ([]Issue, error)
	// All currently-Wanted issues with their normalized sort/qual, for RSS feed matching.
	ListWantedForMatch(ctx context.Context) ([]Issue, error)
	// Idempotent on cache_key (UNIQUE); refreshes payload + freshness markers.
	PutMetadataCache(ctx context.Context, arg PutMetadataCacheParams) error
	SetUserConfig(ctx context.Context, arg SetUserConfigParams) error
	// Flip a download row status (and bump updated_at). All Phase-5 status writes route
	// through the download-status state machine then this query, never a raw caller UPDATE.
	UpdateDownloadStatus(ctx context.Context, arg UpdateDownloadStatusParams) (Download, error)
	UpdateIndexer(ctx context.Context, arg UpdateIndexerParams) (Indexer, error)
	UpdateIssueStatus(ctx context.Context, arg UpdateIssueStatusParams) error
	UpdateSeriesCounts(ctx context.Context, arg UpdateSeriesCountsParams) error
	UpdateSeriesLastRefreshed(ctx context.Context, arg UpdateSeriesLastRefreshedParams) error
	UpdateSeriesSettings(ctx context.Context, arg UpdateSeriesSettingsParams) (Series, error)
	// Idempotent on the immutable comicvine_arc_id.
	UpsertArc(ctx context.Context, arg UpsertArcParams) (StoryArc, error)
	// Idempotent upsert of a cover blob keyed on (entity_type, entity_id).
	UpsertCover(ctx context.Context, arg UpsertCoverParams) error
	UpsertDownloadClientConfig(ctx context.Context, arg UpsertDownloadClientConfigParams) (DownloadClientConfig, error)
	// Idempotent upsert keyed on the immutable comicvine_issue_id.
	UpsertIssue(ctx context.Context, arg UpsertIssueParams) (Issue, error)
	// Idempotent on name (UNIQUE); records the CV publisher id when known.
	UpsertPublisher(ctx context.Context, arg UpsertPublisherParams) (Publisher, error)
	// Idempotent upsert keyed on the immutable comicvine_volume_id.
	UpsertSeries(ctx context.Context, arg UpsertSeriesParams) (Series, error)
}

var _ Querier = (*Queries)(nil)
