// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CountIssuesBySeries(ctx context.Context, seriesID int64) (int64, error)
	CoverExists(ctx context.Context, arg CoverExistsParams) (bool, error)
	GetCover(ctx context.Context, arg GetCoverParams) (GetCoverRow, error)
	GetMetadataCache(ctx context.Context, cacheKey string) (MetadataCache, error)
	GetPublisherByID(ctx context.Context, id int64) (Publisher, error)
	GetSeriesByID(ctx context.Context, id int64) (Series, error)
	GetSeriesByVolumeID(ctx context.Context, comicvineVolumeID int64) (Series, error)
	GetUserConfig(ctx context.Context, key string) (UserConfig, error)
	LinkArcIssue(ctx context.Context, arg LinkArcIssueParams) error
	ListArcsBySeries(ctx context.Context, seriesID int64) ([]StoryArc, error)
	ListIssuesBySeries(ctx context.Context, seriesID int64) ([]Issue, error)
	ListSeries(ctx context.Context, arg ListSeriesParams) ([]Series, error)
	// Active series never refreshed (NULL) or last refreshed before the cutoff, oldest
	// first (NULLs lead). Bounded by LIMIT to keep each sweep tick small. Paused/Ended
	// series are excluded: they are not being watched for freshness.
	ListStaleSeries(ctx context.Context, arg ListStaleSeriesParams) ([]Series, error)
	ListUserConfig(ctx context.Context) ([]UserConfig, error)
	// Idempotent on cache_key (UNIQUE); refreshes payload + freshness markers.
	PutMetadataCache(ctx context.Context, arg PutMetadataCacheParams) error
	SetUserConfig(ctx context.Context, arg SetUserConfigParams) error
	UpdateIssueStatus(ctx context.Context, arg UpdateIssueStatusParams) error
	UpdateSeriesCounts(ctx context.Context, arg UpdateSeriesCountsParams) error
	UpdateSeriesLastRefreshed(ctx context.Context, arg UpdateSeriesLastRefreshedParams) error
	UpdateSeriesSettings(ctx context.Context, arg UpdateSeriesSettingsParams) (Series, error)
	// Idempotent on the immutable comicvine_arc_id.
	UpsertArc(ctx context.Context, arg UpsertArcParams) (StoryArc, error)
	// Idempotent upsert of a cover blob keyed on (entity_type, entity_id).
	UpsertCover(ctx context.Context, arg UpsertCoverParams) error
	// Idempotent upsert keyed on the immutable comicvine_issue_id.
	UpsertIssue(ctx context.Context, arg UpsertIssueParams) (Issue, error)
	// Idempotent on name (UNIQUE); records the CV publisher id when known.
	UpsertPublisher(ctx context.Context, arg UpsertPublisherParams) (Publisher, error)
	// Idempotent upsert keyed on the immutable comicvine_volume_id.
	UpsertSeries(ctx context.Context, arg UpsertSeriesParams) (Series, error)
}

var _ Querier = (*Queries)(nil)
