// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: series.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getSeriesByID = `-- name: GetSeriesByID :one
SELECT id, comicvine_volume_id, publisher_id, name, start_year, description, status, cover_path, total_issues, have_issues, settings_json, last_refreshed_at, created_at FROM series WHERE id = ?
`

func (q *Queries) GetSeriesByID(ctx context.Context, id int64) (Series, error) {
	row := q.db.QueryRowContext(ctx, getSeriesByID, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.ComicvineVolumeID,
		&i.PublisherID,
		&i.Name,
		&i.StartYear,
		&i.Description,
		&i.Status,
		&i.CoverPath,
		&i.TotalIssues,
		&i.HaveIssues,
		&i.SettingsJson,
		&i.LastRefreshedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSeriesByVolumeID = `-- name: GetSeriesByVolumeID :one
SELECT id, comicvine_volume_id, publisher_id, name, start_year, description, status, cover_path, total_issues, have_issues, settings_json, last_refreshed_at, created_at FROM series WHERE comicvine_volume_id = ?
`

func (q *Queries) GetSeriesByVolumeID(ctx context.Context, comicvineVolumeID int64) (Series, error) {
	row := q.db.QueryRowContext(ctx, getSeriesByVolumeID, comicvineVolumeID)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.ComicvineVolumeID,
		&i.PublisherID,
		&i.Name,
		&i.StartYear,
		&i.Description,
		&i.Status,
		&i.CoverPath,
		&i.TotalIssues,
		&i.HaveIssues,
		&i.SettingsJson,
		&i.LastRefreshedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listSeries = `-- name: ListSeries :many
SELECT id, comicvine_volume_id, publisher_id, name, start_year, description, status, cover_path, total_issues, have_issues, settings_json, last_refreshed_at, created_at FROM series
ORDER BY name
LIMIT ? OFFSET ?
`

type ListSeriesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListSeries(ctx context.Context, arg ListSeriesParams) ([]Series, error) {
	rows, err := q.db.QueryContext(ctx, listSeries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Series{}
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.ComicvineVolumeID,
			&i.PublisherID,
			&i.Name,
			&i.StartYear,
			&i.Description,
			&i.Status,
			&i.CoverPath,
			&i.TotalIssues,
			&i.HaveIssues,
			&i.SettingsJson,
			&i.LastRefreshedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSeriesCounts = `-- name: UpdateSeriesCounts :exec
UPDATE series SET total_issues = ?, have_issues = ? WHERE id = ?
`

type UpdateSeriesCountsParams struct {
	TotalIssues int64
	HaveIssues  int64
	ID          int64
}

func (q *Queries) UpdateSeriesCounts(ctx context.Context, arg UpdateSeriesCountsParams) error {
	_, err := q.db.ExecContext(ctx, updateSeriesCounts, arg.TotalIssues, arg.HaveIssues, arg.ID)
	return err
}

const updateSeriesCoverPath = `-- name: UpdateSeriesCoverPath :exec
UPDATE series SET cover_path = ? WHERE id = ?
`

type UpdateSeriesCoverPathParams struct {
	CoverPath sql.NullString
	ID        int64
}

func (q *Queries) UpdateSeriesCoverPath(ctx context.Context, arg UpdateSeriesCoverPathParams) error {
	_, err := q.db.ExecContext(ctx, updateSeriesCoverPath, arg.CoverPath, arg.ID)
	return err
}

const updateSeriesSettings = `-- name: UpdateSeriesSettings :one
UPDATE series SET status = ?, settings_json = ? WHERE id = ?
RETURNING id, comicvine_volume_id, publisher_id, name, start_year, description, status, cover_path, total_issues, have_issues, settings_json, last_refreshed_at, created_at
`

type UpdateSeriesSettingsParams struct {
	Status       string
	SettingsJson sql.NullString
	ID           int64
}

func (q *Queries) UpdateSeriesSettings(ctx context.Context, arg UpdateSeriesSettingsParams) (Series, error) {
	row := q.db.QueryRowContext(ctx, updateSeriesSettings, arg.Status, arg.SettingsJson, arg.ID)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.ComicvineVolumeID,
		&i.PublisherID,
		&i.Name,
		&i.StartYear,
		&i.Description,
		&i.Status,
		&i.CoverPath,
		&i.TotalIssues,
		&i.HaveIssues,
		&i.SettingsJson,
		&i.LastRefreshedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSeries = `-- name: UpsertSeries :one
INSERT INTO series (
  comicvine_volume_id, publisher_id, name, start_year, description,
  status, cover_path, total_issues, have_issues, settings_json,
  last_refreshed_at, created_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(comicvine_volume_id) DO UPDATE SET
  publisher_id      = excluded.publisher_id,
  name              = excluded.name,
  start_year        = excluded.start_year,
  description       = excluded.description,
  cover_path        = excluded.cover_path,
  settings_json     = excluded.settings_json,
  last_refreshed_at = excluded.last_refreshed_at
RETURNING id, comicvine_volume_id, publisher_id, name, start_year, description, status, cover_path, total_issues, have_issues, settings_json, last_refreshed_at, created_at
`

type UpsertSeriesParams struct {
	ComicvineVolumeID int64
	PublisherID       sql.NullInt64
	Name              string
	StartYear         sql.NullInt64
	Description       sql.NullString
	Status            string
	CoverPath         sql.NullString
	TotalIssues       int64
	HaveIssues        int64
	SettingsJson      sql.NullString
	LastRefreshedAt   sql.NullString
	CreatedAt         string
}

// Idempotent upsert keyed on the immutable comicvine_volume_id (META-06).
func (q *Queries) UpsertSeries(ctx context.Context, arg UpsertSeriesParams) (Series, error) {
	row := q.db.QueryRowContext(ctx, upsertSeries,
		arg.ComicvineVolumeID,
		arg.PublisherID,
		arg.Name,
		arg.StartYear,
		arg.Description,
		arg.Status,
		arg.CoverPath,
		arg.TotalIssues,
		arg.HaveIssues,
		arg.SettingsJson,
		arg.LastRefreshedAt,
		arg.CreatedAt,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.ComicvineVolumeID,
		&i.PublisherID,
		&i.Name,
		&i.StartYear,
		&i.Description,
		&i.Status,
		&i.CoverPath,
		&i.TotalIssues,
		&i.HaveIssues,
		&i.SettingsJson,
		&i.LastRefreshedAt,
		&i.CreatedAt,
	)
	return i, err
}
