// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_config.sql

package sqlc

import (
	"context"
)

const getUserConfig = `-- name: GetUserConfig :one
SELECT "key", value FROM user_config WHERE key = ?
`

func (q *Queries) GetUserConfig(ctx context.Context, key string) (UserConfig, error) {
	row := q.db.QueryRowContext(ctx, getUserConfig, key)
	var i UserConfig
	err := row.Scan(&i.Key, &i.Value)
	return i, err
}

const listUserConfig = `-- name: ListUserConfig :many
SELECT "key", value FROM user_config ORDER BY key
`

func (q *Queries) ListUserConfig(ctx context.Context) ([]UserConfig, error) {
	rows, err := q.db.QueryContext(ctx, listUserConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserConfig{}
	for rows.Next() {
		var i UserConfig
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserConfig = `-- name: SetUserConfig :exec
INSERT INTO user_config (key, value)
VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetUserConfigParams struct {
	Key   string
	Value string
}

func (q *Queries) SetUserConfig(ctx context.Context, arg SetUserConfigParams) error {
	_, err := q.db.ExecContext(ctx, setUserConfig, arg.Key, arg.Value)
	return err
}
